### ISSUE TITLE
Right dial in Subtraction Explore

### ISSUE THREAD

**Issue by ehamner** [BirdBrainTechnologies/flutter-kindle-sttr2#40]
In Subtraction Explore, I felt that the right dial should increase the yellow number when it is turned clockwise. In the other arithmetic operations the dials all increase a value when turned clockwise so this felt wrong to me. I would like to see the answer value decrease as I increase the amount that is subtracted.

**Comment by tasota** [comment]
see #43 for discussion

**Comment by bambibrewer** [comment]
And ... now we want to change this one line back. The K and 1 teachers want to subtract by turning the dial to the left.

**Comment by tasota** [comment]
It was 3 lines now, thanks to the difficulty levels! But still rather not-difficult to change back!

<img width="995" alt="screen shot 2019-03-01 at 1 08 39 pm" src="https://user-images.githubusercontent.com/9115672/53657093-2859b380-3c23-11e9-8bf3-8fc9617c12df.png">
