### ISSUE TITLE
Create settings activity

### ISSUE THREAD

**Issue by tasota** [BirdBrainTechnologies/flutter-kindle-sttr2#46]
Recent discussions have indicated that we may want to modify the LED Controllers based on the current level set, so it will be helpful to have this portion implemented.

**Comment by tasota** [comment]
create xml and activity class only (#47 to follow later)

**Comment by tasota** [comment]
might need to look up how to generate capsule-style selection
<img width="406" alt="screen shot 2019-02-05 at 2 00 51 pm" src="https://user-images.githubusercontent.com/9115672/52297325-7fcf7100-294e-11e9-9f2b-b2338cb788c2.png">

**Comment by tasota** [comment]
@bambibrewer would it be possible for you to generate some text for each of these levels for @ashleyli106 to use when designing this screen?

**Comment by tasota** [comment]
@ashleyli106 you can omit Email address for now

**Comment by bambibrewer** [comment]
Absolutely!
Addition Level 1: Adding to 20.
Addition Level 2: Adding to 100 without regrouping.
Addition Level 3: Adding to 120 with regrouping.
Subtraction Level 1: Subtracting to 20.
Subtraction Level 2: Subtracting to 100 without regrouping
Subtraction Level 3: Subtracting to 100 with regrouping.
Multiplication Level 1: Multiplying by 1, 2, 5, 10.
Multiplication Level 2: Multiplying by 1-6, 9, 10.
Multiplication Level 3: Multiplying by 1-12.

**Comment by tasota** [comment]
currently implemented in @ashleyli106 's branch
