### ISSUE TITLE
need assets for Place Value landing screens

### ISSUE THREAD

**Issue by tasota** [BirdBrainTechnologies/flutter-kindle-sttr2#48]
Already have the Explore, Make icons but the remaining 3 for each place value section are still needed (hammer, lt sign, U-arrow; see below).

<img width="424" alt="screen shot 2019-02-07 at 2 51 56 pm" src="https://user-images.githubusercontent.com/9115672/52438765-02d7ff00-2ae8-11e9-8e0e-2f51ba1687c4.png">

**Comment by mo11yj** [comment]
Added: zpl://screen?pid=5b9467c8163d2c1085a06a85&sid=5c6891bee66ab39ac1d163d4
