### ISSUE TITLE
assets for choose math section

### ISSUE THREAD

**Issue by tasota** [BirdBrainTechnologies/flutter-kindle-sttr2#53]
Would it be possible to get separate asset images for the icons highlighted below? The black gear is part of an asset called "app-header" but it also includes the Flutter text in it.

<img width="806" alt="landing_selected" src="https://user-images.githubusercontent.com/9115672/52811273-af732d00-3062-11e9-9511-bec21d76510d.png">

**Comment by mo11yj** [comment]
Added: zpl://screen?pid=5b9467c8163d2c1085a06a85&sid=5c46451fc8eb52379d40cec8
