### ISSUE TITLE
Don't show the number in Make until you check the answer.

### ISSUE THREAD

**Issue by ehamner** [BirdBrainTechnologies/flutter-kindle-sttr2#55]
Don't show the number in Make until you check the answer. (Maybe some a different visual?)

**Comment by ehamner** [comment]
@bambibrewer is this what teachers wanted?

**Comment by bambibrewer** [comment]
Before I answer, are we talking about CubeTower or GlowGrid?

**Comment by ehamner** [comment]
CubeTower

**Comment by bambibrewer** [comment]
Yes, I believe that is what the teachers wanted.

**Comment by lczito** [comment]
What if we showed the blocks on the screen as they add cubes to the columns?

**Comment by bambibrewer** [comment]
It seems a little off to add that visual in just one place, because it doesn't appear anywhere else in the app (unlike the array in GlowGrid). I do remember at least some teachers expressing that, but I think I would leave the number representations for now and see if they ask in the pilots for us to remove them.

**Comment by tasota** [comment]
The visual does display right now in the explore section. Here's an example from Hundreds:

<img width="812" alt="screen shot 2019-02-18 at 2 10 28 pm" src="https://user-images.githubusercontent.com/9115672/52971889-12c4ce00-3387-11e9-8a75-a43c74464fe7.png">

I could imagine replacing the numbers in Make with just the visual representation, if you wanted to avoid the numbers showing on the screen

**Comment by lczito** [comment]
Thanks, Mike! That is exactly what I was thinking

**Comment by ehamner** [comment]
I imagine something like a generic loading/waiting animation or question marks.
@mo11yj any thoughts?

**Comment by lczito** [comment]
Or a lightly falling blocks animation?

**Comment by mo11yj** [comment]
I like the idea of question marks, we could show the blocks graphic, but I do think that would feel pretty different than the rest of the app, and when you check answer that could be a lot of things changing on the screen. I like the idea of the screen staying very simple and static if we want them to be focused on the manipulative.

**Comment by ehamner** [comment]
Will you make us some question mark icons?

**Comment by mo11yj** [comment]
Make Screens: 
zpl.io/a3eXpYN
https://app.zeplin.io/project/5b9467c8163d2c1085a06a85/screen/5c46451d564c153791492f96
https://app.zeplin.io/project/5b9467c8163d2c1085a06a85/screen/5c46451c35c1a337cd943615
https://app.zeplin.io/project/5b9467c8163d2c1085a06a85/screen/5c46451050e77937aff90033
https://app.zeplin.io/project/5b9467c8163d2c1085a06a85/screen/5c464514143de2bfcbf399b8
https://app.zeplin.io/project/5b9467c8163d2c1085a06a85/screen/5c464515143de2bfcbf399df

Updated in zeplin, icons should be exportable

**Comment by tasota** [comment]
Thank you Molly!

So question: after the user presses the button and the number displays with the 'try again' prompt, what should the behavior be when they start to modify the number again? Should it stay static with the previously wrong answer, or should it switch over to question marks again as soon as they start moving  blocks?

The latter option makes more sense to me but I wanted feedback from others @mo11yj @ehamner @lczito @bambibrewer

**Comment by ehamner** [comment]
I think question marks, or it could switch to the behavior where it shows the number live updating as a scaffold after you have gotten it wrong once. What do others think?

**Comment by lczito** [comment]
Question marks feel like a more consistent response than the static number, but I could also see it live update after getting it wrong. I think we would need more scaffolded behavior across both apps for that to feel more natural though

**Comment by bambibrewer** [comment]
I agree with Lauren that the question marks feel more consistent for now. I think we can decide after the first pilots if we need more scaffolding.

**Comment by tasota** [comment]
Thanks all. I will work on having this behavior ready for the pilot

**Comment by bambibrewer** [comment]
The K and 1 teachers actually don't want the question marks, they want the live updates for the numbers, so I am reopening this issue.

**Comment by tasota** [comment]
just emailed you; a20ae31448643573853d3f0641825ee9c1e8609c 😂
