### ISSUE TITLE
Unable to see Flutter when scanning

### ISSUE THREAD

**Issue by bambibrewer** [BirdBrainTechnologies/flutter-kindle-sttr2#61]
A lot of the time when I open the app, I can't see the Flutter. I have to unplug and replug it and scan again a couple of times before I can actually see it and connect. Also, I notice the spinning arrow stops pretty quickly. How long are you scanning?

**Comment by tasota** [comment]
scan is currently set at 2 seconds. How long should we have this scan for? 5 seconds? 10 seconds?

**Comment by bambibrewer** [comment]
Is there a downside to continuing to scan until the user connects?

**Comment by tasota** [comment]
Not as far as I know. I will create a separate issue for implementing that logic.

As for the core of this issue (flutters not appearing without power cycling) it is unclear if changing scan time will resolve this, so leaving this one open as well.

**Comment by bambibrewer** [comment]
I have noticed that it sometimes takes bluetooth devices longer to show up on Kindles, so it may be that I chose to power cycle when I actually should have kept hitting the scan button, but I agree with leaving the issue open until we see.

**Comment by bambibrewer** [comment]
This is way better!

**Comment by tasota** [comment]
Hooray! :)

I'll mark as "validate resolved" until the first pilot, in case it still shows up down the line.
