### ISSUE TITLE
Change problem generation for Addition Level 1

### ISSUE THREAD

**Issue by bambibrewer** [BirdBrainTechnologies/flutter-kindle-sttr2#65]
For Addition Level 1, can we modify Solve and Find so that both numbers are generated from 0-10 (currently the first is 0-10 and then the second is 0 to 10-first number, but having tried it, I think both being 0-10 would be better).

**Comment by tasota** [comment]
Alright, just changed it!

**Comment by bambibrewer** [comment]
You are awesome, thank you!
