### ISSUE TITLE
Color corrections for Addition/Subtraction

### ISSUE THREAD

**Issue by bambibrewer** [BirdBrainTechnologies/flutter-kindle-sttr2#66]
Currently, the "second number" LEDs are red in Addition on the LED Array, but yellow in the app. Can they be red in the app to match?

For subtraction, the numbers in the equations in Explore are blue and yellow, the array in the app is orange and dim orange, and on the LED Array, the colors are red and dim red. I think the equation needs to match the other representations, and I would say the app should be red and dim red to match the LED array. Other thoughts?

**Comment by tasota** [comment]
for Addition, the current second color is [#e9c422](https://duckduckgo.com/?q=color+%23e9c422&atb=v5&ia=answer)

Replace with... some particular shade of red? I imagine pure red (ff0000) is too much.

Does @mo11yj have any color code suggestions for a bright red and dim red to use for the app screen?

**Comment by bambibrewer** [comment]
I am completely happy to leave this one up to @mo11yj but I think she is on vacation till Tuesday.

**Comment by tasota** [comment]
Here's what I have it as currently. We can always update if molly has some better color recommendations. The red on addition is just ff0000; the colors in subtraction are from the designs (which were different before in the code for some reason).

## Explore Addition
![screenshot_2019-03-04-09-15-26](https://user-images.githubusercontent.com/9115672/53738816-3ba49300-3e5e-11e9-8115-ad935f769b31.png)

## Explore Subtraction
![screenshot_2019-03-04-09-15-33](https://user-images.githubusercontent.com/9115672/53738823-3f381a00-3e5e-11e9-9e49-78ab0d401c50.png)

**Comment by mo11yj** [comment]
Can we use: #C53748 for the red? that will match the red/pink color we use in the place value app.

**Comment by tasota** [comment]
Thank you Molly!

![screenshot_2019-03-05-17-33-44](https://user-images.githubusercontent.com/9115672/53842227-e1debe80-3f6c-11e9-8656-aa1c375b3b61.png)

**Comment by bambibrewer** [comment]
Should we use the red (and a darker red) in the Subtraction mode too? It seems a little odd that the color is the same on the LED array but different in the app.

**Comment by tasota** [comment]
My only concern would be if the reds would look strange in an orange-themed screen

**Comment by tasota** [comment]
Alright, here's a quick comparison. @bambibrewer @ehamner @mo11yj what do you all think?

## Orange
![screenshot_2019-03-04-09-15-33](https://user-images.githubusercontent.com/9115672/53738823-3f381a00-3e5e-11e9-9e49-78ab0d401c50.png)

## Darker Red
![screenshot_2019-03-06-12-47-13](https://user-images.githubusercontent.com/9115672/53901917-13f42d00-400e-11e9-943c-30daebc2788b.png)

**Comment by tasota** [comment]
Emily says go with darker red

**Comment by bambibrewer** [comment]
Personally, I like having it match the LEDs (I presume the darker would change to a darker version of the red?), but I am flexible. 

Either way, shouldn't the large number (16 in this instance) be a different color from the number being subtracted?

**Comment by bambibrewer** [comment]
Or, we could change LEDs and display to blue if it goes with orange better.

**Comment by tasota** [comment]
Sounds like darker red is the preference.

The issue with this first number I believe is that it is not directly represented by the color change. The difference is one color and the subtrehend is another, but that first number is just the collective highlighted terms.

**Comment by bambibrewer** [comment]
Yes, that is true - it is similar to the sum in addition. There, it looks like it is a darker shade of the background color, and that distinguishes it from the blue and the red. Here, I think the issue is that we are using the darker background color shade for two numbers.

**Comment by tasota** [comment]
Ah, okay i see. What about using the prior orange? See below:

![screenshot_2019-03-06-13-28-37](https://user-images.githubusercontent.com/9115672/53904347-d5617100-4013-11e9-855e-2647e5fe179c.png)

**Comment by bambibrewer** [comment]
I'm fine with that!

**Comment by tasota** [comment]
Excellent! pushing out my changes now and will update pilot1 branch shortly
