### ISSUE TITLE
place_value: icons for red (money) section

### ISSUE THREAD

**Issue by tasota** [BirdBrainTechnologies/flutter-kindle-sttr2#68]
I was working on #63 when I noticed we don't have any of the icons downloadable for the money section. @mo11yj could you add to zeplin when you get a chance?

<img width="802" alt="screen shot 2019-02-26 at 10 05 15 am" src="https://user-images.githubusercontent.com/9115672/53422766-158a7900-39ae-11e9-88bc-6eed6035a6c7.png">

**Comment by mo11yj** [comment]
zpl://screen?sid=5c6891bee66ab39ac1d163d4&pid=5b9467c8163d2c1085a06a85

Updated

**Comment by tasota** [comment]
Hm. I see them on the place value icons screen now but I don't see them as downloadable assets?

**Comment by tasota** [comment]
nevermind they are good now, thank you!

**Comment by mo11yj** [comment]
oops, sorry, try now

I wish zeplin just did that automatically...

**Comment by tasota** [comment]
> I wish zeplin just did that automatically...

Same! 😂
