### ISSUE TITLE
Darker Flutter outline for scanning screen

### ISSUE THREAD

**Issue by bambibrewer** [BirdBrainTechnologies/flutter-kindle-sttr2#69]
I am so excited that the colors show up when you are scanning now, but Raghu and I had a hard time seeing the Flutter outline around them (so he didn't know how to orient the Flutter, since he didn't know the outline was supposed to tell him). Could we make the outline darker so it is more visible?

**Comment by tasota** [comment]
So here's from the **designs**:
<img width="803" alt="screen shot 2019-02-28 at 9 59 44 am" src="https://user-images.githubusercontent.com/9115672/53575474-9f1d8080-3b3f-11e9-9f43-f488ab517bee.png">

And here's from the actual **app's screenshot**:
![screenshot_2019-02-28-09-59-48](https://user-images.githubusercontent.com/9115672/53575549-cb390180-3b3f-11e9-82b2-d428c812e7c1.png)

Here's a slightly darker version that I mocked up by modifying the flutter outline SVG:
![screenshot_2019-02-28-10-09-43](https://user-images.githubusercontent.com/9115672/53576198-23bcce80-3b41-11e9-85bf-003d26103a69.png)

Dark enough? Too dark?

**Comment by bambibrewer** [comment]
I think it looks just dark enough!

**Comment by mo11yj** [comment]
agreed, looks good to me!

**Comment by tasota** [comment]
Great! 😁
