### ISSUE TITLE
Visualizations for Explore in CubeTower

### ISSUE THREAD

**Issue by bambibrewer** [BirdBrainTechnologies/flutter-kindle-sttr2#71]
Seeing the visualizations for Explore in CubeTower (Tens and Hundreds modes) is a priority for the K and 1 pilots.

**Comment by tasota** [comment]
<img width="797" alt="screen shot 2019-03-01 at 1 04 58 pm" src="https://user-images.githubusercontent.com/9115672/53656888-a4073080-3c22-11e9-80ba-a46de804687a.png">

**Comment by tasota** [comment]
@mo11yj would you be able to make each block style above into its own image resource? I know we were discussing this before and I think that making these shapes as primitives in the app would slow things down a lot. The purple block is easy for me to make on my end (just 1 rectangle), but for the other two maybe as transparent images?

**Comment by tasota** [comment]
I have something basic for now (see screenshot below) but we can update with assets once they are available.

![screenshot_2019-03-04-10-14-51](https://user-images.githubusercontent.com/9115672/53743376-afe43400-3e68-11e9-9e43-d43a6b4cce69.png)

**Comment by mo11yj** [comment]
I uploaded assets to zeplin on that page: zpl://screen?sid=5c46451f564c153791492fdc&pid=5b9467c8163d2c1085a06a85

**Comment by tasota** [comment]
Thank you @mo11yj! I will update this shortly.

By the way I accidentally split a section on Zeplin again, sorry about that! 😂

**Comment by tasota** [comment]
This looks really cool now!

![screenshot_2019-03-05-17-41-18](https://user-images.githubusercontent.com/9115672/53842661-20c14400-3f6e-11e9-8b57-32deca0f1e06.png)

Direction change still being discussed in #74

**Comment by bambibrewer** [comment]
@tasota Is this in the Pilot 1 branch? I just loaded it onto my Kindle this morning, but I don't see the visualizations.

**Comment by tasota** [comment]
this commit 7b258427cef9188a4934fd86df1ddc6c634bb337 is now in pilot1 branch
