### ISSUE TITLE
Pilot 1 - should we remove non functional buttons

### ISSUE THREAD

**Issue by bambibrewer** [BirdBrainTechnologies/flutter-kindle-sttr2#77]
I noticed in testing the Pilot 1 branch that the "Continue Session" button is there at the beginning, and all of the activities appear for the modes. Should we remove the buttons for "Make" and "Create" for GlowGrid and "Build", "Compare", and "Round" for CubeTower to match what the teachers were trained with? @ehamner @tasota

**Comment by tasota** [comment]
Yes I definitely think it makes sense to hide anything nonfunctional as we did for the PD. When I merge the visualization changes to 'pilot1' I will also add this and will email everyone again when it is ready. Waiting for confirmation in #66

**Comment by tasota** [comment]
50b50af99cb71bafd67faffc0ebb65034382fad0
