### ISSUE TITLE
Switch direction of dials for subtraction

### ISSUE THREAD

**Issue by ehamner** [BirdBrainTechnologies/flutter-kindle-sttr2#80]
(Observed in Pilot 1, Kindergarten)
The direction of the dials in subtraction was very confusing for the kids. We want to switch it back to the way it was - so it matches the direction in addition - for the 1st grade pilot next week.

@tasota if you can make the change Friday, @bambibrewer will update the kindles.

**Comment by tasota** [comment]
19a88a712c1be0abdd702cd17ebdd6cb1363f174

The linked APK is also updated with branch `pilot1-v2` (only for glowgrid since the other is unaffected by this)
