### ISSUE TITLE
change button text in Make Exercises

### ISSUE THREAD

**Issue by tasota** [BirdBrainTechnologies/flutter-kindle-sttr2#93]
I think this was mentioned in another issue but I can't find it right now. Instead of having different text for each button (example: "Check Difference" or "Check Product") just have all of them read "Check Answer" instead.

**Comment by bambibrewer** [comment]
@tasota This was only for Find, not Make - we want to leave the buttons in Make the way they are (sum, product, etc.)

**Comment by tasota** [comment]
Ah alright sorry for the confusion there.
